### ISSUE TITLE
RCON Stats not exported with 1.16.1

### ISSUE THREAD

**Issue by soguertler** [Joshi425/minecraft-exporter#10]
I'm running 1.16.1 Paper and I'm getting all the usual stats except the RCON ones.
RCON seems to connect fine since I don't get any errors in the logs.

**Comment by Joshi425** [comment]
is the player_online metric working for you?
the tps metrics are only working on forge servers right now, because the use `forge tps`

**Comment by soguertler** [comment]
All of these aren't working:
`dim_tps`
`dim_ticktime`
`overall_tps`
`overall_ticktime`
`player_online`

**Comment by Joshi425** [comment]
I've just tested with `git-Paper-157 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)`
the player_online metric is working there:
```
[16:53:40 INFO]: There are 0 of a max of 20 players online:
[16:55:20 INFO]: UUID of player Joshi425 is 019b5483-787e-4386-9f1c-b2e3f86b7a3f
[16:55:20 INFO]: Joshi425 joined the game
[16:55:20 INFO]: Joshi425[/91.10.199.167:49752] logged in with entity id 305 at ([world]237.5, 71.0, 179.5)
> list
[16:56:39 INFO]: There are 1 of a max of 20 players online: Joshi425
```

```
root@test:~# curl -s localhost:8000/metrics |grep player_online
# HELP player_online_total is 1 if player is online
# TYPE player_online_total counter
player_online{player="Joshi425"} 1.0
```
the other metrics are only supported on forge servers, since they use the command `forge tps` to get the tps information for each dimension.
Paper has a `tps` command, I will look into if I can implement that in the exporter

**Comment by soguertler** [comment]
Well then it seems to be some other issue on my end.

I'm going to close the issue for now and I'll post an update if I locate the problem.
